# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

from pathlib import Path

readme = ""
pkg = "bimaxpy"

setup(
    long_description=readme,
    name=pkg,
    version="0.1.0",
    description="python bindings for bimax algorithm written in go",
    python_requires="==3.*,>=3.6.0",
    author="Max Schulte",
    packages=[pkg],
    package_dir={"": "."},
    install_requires=["cffi==1.*,>=1.14.4"],
    cffi_modules=["build.py:ffi"],
)
