
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='bimaxpy',
    version='0.1.0',
    description='python bindings for bimax algorithm written in go',
    python_requires='==3.*,>=3.6.0',
    author='Your Name',
    author_email='you@example.com',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['cffi==1.*,>=1.14.4'],
)
